# Generated by Django 3.2.5 on 2021-08-08 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210804_1638'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='ShoppingCar',
        ),
        migrations.AlterModelOptions(
            name='shoppingcar',
            options={'verbose_name': 'Shopping Car', 'verbose_name_plural': 'Shopping Cars'},
        ),
        migrations.AlterModelTable(
            name='shoppingcar',
            table='shopping_cars',
        ),
    ]
