# Generated by Django 3.2.5 on 2021-07-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sesion', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
            ],
            options={
                'verbose_name': 'Sesion',
                'verbose_name_plural': 'Sesiones',
                'db_table': 'sesiones',
                'ordering': ['sesion'],
            },
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semana', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('id_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sesion')),
            ],
            options={
                'verbose_name': 'Semana',
                'verbose_name_plural': 'Semanas',
                'db_table': 'semanas',
                'ordering': ['semana'],
            },
        ),
    ]
