# Generated by Django 3.2.5 on 2021-07-29 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_semana_sesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='id_curso',
        ),
        migrations.CreateModel(
            name='SesionCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
                ('id_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sesion')),
            ],
            options={
                'verbose_name': 'Sesion de Curso',
                'verbose_name_plural': 'Sesion de Cursos',
                'db_table': 'sesion_cursos',
            },
        ),
    ]
