# Generated by Django 3.2.5 on 2021-07-30 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210729_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semana',
            old_name='id_SesionCurso',
            new_name='id_sesioncurso',
        ),
    ]
