# Generated by Django 3.2.5 on 2021-08-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210730_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CursoBeneficio',
        ),
    ]
