# Generated by Django 3.2.5 on 2021-08-03 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_descuento_interesado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
