# Generated by Django 3.2.5 on 2021-08-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_descuento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='codigo',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
