# Generated by Django 3.2.5 on 2021-08-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cursodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursodetalle',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
