# Generated by Django 3.2.5 on 2021-08-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_cursodetalle_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursodetalle',
            options={'ordering': ['id'], 'verbose_name': 'Curso Detalle', 'verbose_name_plural': 'Cursos Detalles'},
        ),
        migrations.AlterModelTable(
            name='cursodetalle',
            table='curso_detalle',
        ),
    ]
